### ISSUE TITLE
`debcvescan version` returns product version 0.0.0

### ISSUE THREAD

**Issue by m-ueberall** [devmatic-it/debcvescan#2]
(Tested using the release packages [debcvescan_0.1.17_linux_amd64.deb](https://github.com/devmatic-it/debcvescan/releases/download/v0.1.17/debcvescan_0.1.17_linux_amd64.deb) and [debcvescan_0.1.17_linux_arm64.deb](https://github.com/devmatic-it/debcvescan/releases/download/v0.1.17/debcvescan_0.1.17_linux_arm64.deb).)
IMHO, the reported product version should be identical to the package version.

**Comment by batorfc** [comment]
Should be fixed now.

**Comment by batorfc** [comment]
fixed in 0.1.18 version
